spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "helloworld"
trigger = { type = "http", base = "/" }
version = "1.0.4"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/spinhelloworld.wasm"
description = "A simple component that returns hello."
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"
